%YAML 1.2
---
address:
  parents:
    - [network, network]
    - [vnic, vnic]
  pkey: uuid

bond:
  parents:
    - [host, host]
  pkey: uuid

cluster:
  parents:
    - [tenant, tenant]
  pkey: uuid

cluster_instance:
  parents:
    - [cluster, cluster]
    - [instance, instance]
  pkey: uuid

config:
  parents: []
  pkey: key

cpu_profile:
  parents: []
  pkey: uuid
  public: true

disk:
  parents:
    - [storage_pool, storage_pool]
  pkey: id

event:
  parents:
    - [host, host]
    - [instance, instance]
  pkey: hash

extent:
  parents:
    - [storage_pool, storage_pool]
    - [volume, volume]
  pkey: uuid

host:
  parents: []
  pkey: uuid

image:
  parents:
    - [tenant, tenant]
  pkey: uuid
  public: true

instance:
  parents:
    - [cpu_profile, cpu_profile]
    - [tenant, tenant]
  pkey: uuid

member:
  parents:
    - [tenant, tenant]
    - [user, user]
  pkey: uuid

network:
  parents:
    - [switch, switch]
  pkey: uuid
  public: true

nic:
  parents:
    - [host, host]
    - [bond, bond]
  pkey: hwaddr

nic_role:
  parents:
    - [bond, bond]
  pkey: uuid

quota:
  parents:
    - [tenant, tenant]
  pkey: uuid

route:
  parents:
    - [network, network]
  pkey: uuid

storage_pool:
  parents: []
  pkey: uuid
  public: true

switch:
  parents:
    - [tenant, tenant]
  pkey: uuid

tenant:
  parents: []
  pkey: uuid

user:
  parents: []
  pkey: email

vdisk:
  parents:
    - [instance, instance]
    - [volume, volume]
    - [storage_pool, storage_pool]
  pkey: uuid

vnic:
  parents:
    - [instance, instance]
    - [switch, switch]
  pkey: uuid

volume:
  parents:
    - [storage_pool, storage_pool]
    - [tenant, tenant]
  pkey: uuid

